name: 'metal-actions-example'

on:
  workflow_dispatch:

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
#     - name: Create temporary project
#       id: metal-project
#       uses: equinix-labs/metal-project-action@main
#       with:
#         userToken: ${{ secrets.METAL_AUTH_TOKEN }}
    - name: Use the Project SSH Key outputs (display it)
      run: |
        echo $PROJECT_PRIVATE_SSH_KEY
        echo $PROJECT_PUBLIC_SSH_KEY
    - name: Use the Project ID outputs (display it)
      run: |
        echo Equinix Metal Project "${{ env.PROJECT_NAME }}" has ID "${{ env.PROJECT_ID }}"
    - name: Create device in temporary project
      uses: equinix-labs/metal-device-action@main
#       continue-on-error: true
      with:
        metal_auth_token: ${{ secrets.METAL_AUTH_TOKEN }}
        metal_project_id: ${{ env.PROJECT_ID }}
        metro: da
        plan: m3.small.x86
        os: ubuntu_22_04
